version: '3.7'

services:
  rusty:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
      - ./log:/code/log
      - ./config:/code/config
      - ./Cargo.lock:/code/Cargo.lock
      - ./Cargo.toml:/code/Cargo.toml
    ports:
      - 8090:8090
    environment:
      - RUST_BACKTRACE=1
