version: '3.7'

services:
  rusty:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
      - ./log:/code/log
      - ./config:/code/config
      - ./output:/code/output
      - ./Cargo.lock:/code/Cargo.lock
      - ./Cargo.toml:/code/Cargo.toml
      - ../dataframe:/dataframe
    environment:
      - RUST_BACKTRACE=1
