refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: log/app.log
    encoder:
      pattern:  "{d} [{1}]  - {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - file


# loggers: 
#   app:backend::db:
#     level: info
#   app:file:
#     level: info
#     appenders:
#       - file
#     additive: false
    